version: "3"

services:
  web:
    build: .
    expose:
      - 5000
    command: flask run
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
#      - redis
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgresSava
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


#  redis:
#    image: "redis:alpine"
#    ports:
#    - 6379:6379